variable "region" {}
variable "cluster_name" {}
variable "resource_group" {}
variable "mysql_password" {}
variable "service_name" {}
variable "mysql_name" {}
variable "mysql_sku_name" {}
variable "mysql_capacity" {}
variable "mysql_username" {}
